src/components/_menus/ModalMenu/Menu.tsx
Fixes #267 
This PR introduces a fix to the validation logic that was blocking max deposits.
gas fees are absurd right now, so couldn't fully test a deposit flow, but the UI is no longer blocking on a max deposit.
=> fixed: validation logic for deposits

src/components/_cards/CellarCard/index.tsx, src/components/_modals/DepositModal.tsx, src/components/_pages/PageCellar.tsx, src/data/cellarDataMap.ts
Fixes #52
Updated APY values to pull in hardcoded value from `cellarDataMap` instead of the subgraph.
=> refactored components to pull in apy from cellarDataMap

src/components/_cards/SwapSettingsCard.tsx, src/components/_modals/DepositModal.tsx, src/utils/config.ts
Sets a default slippage value for Uniswap swaps through the `CellarRouter` and adds the option for users to change the slippage tolerance through the UI.
=> Change default slippage and add slippage config

src/components/TokenAssets/index.tsx, src/components/_menus/ModalMenu/Menu.tsx, src/components/_modals/DepositModal.tsx
Changes the default selected token in the deposit modal to the cellar's active asset.
=> change default selected deposit token to active asset

src/components/_cards/PortfolioCard.tsx
Fixes the PNL calculation and shows PNL to 5 decimals precision.
- Lower case address before querying subgraph
- Show PNL with 2 decimals
- Add 5 decimal place PNL in tooltip
=> PNL: Use lowercase address when querying subgraph.

src/components/_menus/ModalMenu/Menu.tsx, src/components/_modals/DepositModal.tsx, src/generated/subgraph.ts, src/queries/get-current-deposits.graphql
Fixes #239 
This PR introduces the validation logic to make sure a user's current balance is below the cellar deposit limit.
=> Deposit limit

src/components/CellarStats.tsx, src/components/_pages/PageCellar.tsx
Fixes #367
This PR fixes the logic used to calculate the cellar cap value.
=> fixed cellar cap

src/components/_cards/CellarDetailsCard.tsx, src/data/cellarDataMap.ts
Fixes #361
This PR introduces changes to the performance split chart.
=> Performance fee

src/components/_charts/TVLChart.tsx, src/context/performanceChartContext.tsx, src/utils/urql.ts
Fixes #399
This PR introduces fix to bug that was causing nivo chart to represent 1mil as... 1 😅
=> found solve for tvm chart vals

src/context/performanceChartContext.tsx
Fixes #386
This PR introduces new logic that sets the default value of the TVM chart header to be the latest daily entry
=> TVM default values

src/components/_menus/ModalMenu/Menu.tsx
Fixes #386
This PR introduces a `clearErrors()` step when a new token is selected in the deposit modal menu. It should resolve the insufficient funds bug.
=> clear errors on token select

src/components/_buttons/ConnectButton/index.tsx
Fixes #407 
If the customer has not installed Metamask currently we show button names "Please install MetaMask".
As standard practice by others is also first to show “Connect wallet” and later point out or direct to install Metamask, we will change it the same way.
=> updated connect button copy

src/components/_cards/BondingTableCard.tsx, src/components/_forms/BondForm/index.tsx
Fixes #360 
Add more proper `gasLimit` 
Gas used estimated 120.000 - 140.000
Before: 
`gasLimit` 1.000.000
After:
`gasLimit` 200.000
Gas used estimated around 63.000
Before:
`gasLimit` 1.000.000
After: 
`gasLimit` 80.000
=> feat(contracts): add more proper gasLimit

src/components/_modals/BondModal.tsx, src/components/_modals/WithdrawModal.tsx
Fixes #447 
`toEther` need to set format false to show the correct amount
=> fix(ui): ether convertion without format

src/components/Layout.tsx, src/components/_banners/WrongNetworkBanner.tsx
Closes #461 
Show a banner if the user is not in ethereum chain and ability to switch to ethereum
https://user-images.githubusercontent.com/39829726/192366357-58ad3599-e539-438b-9281-54bb2e245fe0.mp4
=> feat: wrong network banner

src/components/_cards/PortfolioCard.tsx, src/components/_menus/ModalMenu/Menu.tsx, src/components/_modals/DepositModal.tsx, src/data/tokenConfig.ts
Separating `tokenConfig` and `depositAssetTokenConfig` because it is used to contain token config, so if we want to add more token config we can add it there
=> refactor: separate tokenConfig and depositAssetTokenConfig

src/components/_cards/PortfolioCard/index.tsx
Fixes Sell button disabled if the value below 1. appearently `parseInt` causes this bug happen
- go to one of the cellar manage page
- deposit/buy below 1 lp token (0. ) 
- check sell button is disabled or not
=> fix: sell button disabled if the value below 1

src/components/_menus/ModalMenu/Menu.tsx, src/components/_menus/ModalMenu/index.tsx, src/components/_modals/DepositModal.tsx, src/data/strategies/aave-stable.ts, src/data/strategies/eth-btc-momentum.ts, src/data/strategies/eth-btc-trend.ts, src/data/tokenConfig.ts, src/data/types.ts
https://github.com/orgs/strangelove-ventures/projects/11
Adds ETH and BTC as deposit assets for the cleargate cellars
- Makes deposit token list configurable per cellar
- Adds ETH and BTC to cleargate cellars only
- Aave cellar is configured with existing list (no ETH or BTC)
Cleargate list
Aave list
=> Make deposit token list configurable per cellar

src/components/_menus/ModalMenu/Menu.tsx
If decimals is too many the available balance is always 0. So I added 6 decimals to show available balance
=> fix: add more decimals to show on available balance

src/components/_cards/PortfolioCard/index.tsx
Update for #555 
Update tooltip to use cellarDataMap depositToken list 
aave
ETH-BTC Trend & ETH-BTC Momentum
=> feat: update tooltip to use depositTokens list

src/components/_cards/PortfolioCard/index.tsx
#547 
remove bond button from aave cellar view
=> feat: remove bond button from aave cellar view

src/data/actions/AAVE_V2_STABLE_CELLAR/getApy.ts
#628 
Comment out aave strategy apy, because of rebalancing, Aave APY is 0.00% for the week.
=> feat: comment out aave strategy apy

src/components/PercentageHeading.tsx, src/components/PercentageText.tsx, src/components/_icons/MinusIcon.tsx, src/components/_icons/PlusIcon.tsx
#632 
Implement design feedback for percentage text
positive value
negative value
=> update percentage text and icon

src/components/PercentageText.tsx
add more spacing on percentage text
=> feat: add more spacing on percentage text

src/components/PercentageText.tsx, src/components/_charts/EthBtcChart.tsx, src/data/actions/common/getEthBtcGainChartData.ts, src/data/context/ethBtcChartContext.tsx, src/utils/chartHelper.ts
ETH BTC Chart
The right calculation for percentage on the chart is compared to the first data not the previous data
=> Feat(eth btc chart)/change comparation to first data

src/components/CellarStatsAutomated.tsx, src/components/CellarStatsYield.tsx, src/components/HeroStrategy/hero-right.tsx, src/components/Layout.tsx, src/components/StrategyProvider.tsx, src/components/_cards/CellarDetailsCard.tsx, src/components/_cards/EthBtcPerfomanceCard.tsx, src/components/_cards/PerformanceCard.tsx, src/components/_cards/StrategyBreakdownCard/index.tsx, src/components/_cards/TransparentCard.tsx, src/components/_charts/EthBtcChart.tsx, src/components/_charts/TVLChart.tsx, src/components/_layout/Section.tsx, src/components/_pages/PageCellar.tsx, src/components/_pages/PageHome.tsx, src/components/_pages/PageStrategy.tsx
#356 
Working on the first responsive iteration for strategy detail page, update "Explore strategies button" to open in the same page, update Icon in strategy landing page hero section
=> feat: first responsive iteration

src/components/_buttons/ConnectButton/index.tsx, src/components/_modals/DepositModal/SommelierTab.tsx, src/components/_pages/PageHome.tsx, src/utils/landingType.ts
- Identifies connected users by wallet address
- Sends cellar name and address to deposit events
- Add new events for tracking direct and indirect strategy card selection as requested by Owldon
=> Send cellar id and name to deposit events, track wallet address

src/components/HeroStrategy/hero-right.tsx
Fixes #680 
Change manage portofolio to view details
=> feat: change manage portofolio to view details

src/components/_cards/BondingTableCard.tsx
Fixes #718 
`ethers.BigNumberish` doesn't pickup `toString` ex: `1e+21` need to Change it to `toFixed`
=> fix: bonding amount > 1k

src/components/_cards/PortfolioCard/index.tsx
Fixes #709 
add info block in strategy details page
=> feat: add info block in strategy details page

env.d.ts, src/pages/_document.tsx, src/utils/analytics.ts
Fixes Analytics event not sending to google tag manager's `window.dataLayer`
1. open https://sommelier-drmnapxik-sommelierfinance.vercel.app/
2. click one of the cards
3. open console
4. check `dataLayer` object it should have `strategy.selection` event
=> fix: rework gtm to trigger with window.dataLayer.push

src/components/_charts/ApyChart.tsx, src/components/_charts/EthBtcChart.tsx, src/components/_charts/TokenPriceChart.tsx, src/components/_charts/UsdcChart.tsx
Fixes #998 
chart quick update
=> feat: chart quick update

src/components/_charts/ApyChart.tsx, src/components/_charts/EthBtcChart.tsx, src/components/_charts/TokenPriceChart.tsx, src/components/_charts/UsdcChart.tsx
Fixes #1059 
if the data is less then 30, then when the timeframe was `all` it will show every 3 days.
if the data is less then 120, then when the timeframe was `all` it will show every 5 days.
=> fix: old chart reponsive and months view

src/data/actions/common/getUserData.ts
This value was denoted in shares and not assets. Multiplying shares by shareValue will convert it to the base asset value.
=> Convert shares -> asset for value netValueWithoutRewardsInAsset

src/data/actions/CELLAR_V2/getBaseApy.ts, src/data/actions/common/getApyInception.ts, src/data/actions/common/getStrategyData.ts, src/data/strategies/eth-btc-trend.ts, src/data/types.ts
- Rename old v2 `getBaseApy` to common `getApyInception`
- Allow configurable starting value for `shareValue`
- Configure ETH-BTC Trend Cellar correct starting share value
- Migrate all cellars to use since inception APY calc
=> Migrate v1 & v1.5 cellars to use APY since inception

src/data/actions/common/getUserData.ts
Bug, user deposited $950 but net value is showing $969 and user has no rewards:
Fixed:
=> Multiply totalAssets by asset price, not cellar share value

src/components/_modals/DepositModal/SommelierTab.tsx
Fixes #<https://github.com/strangelove-ventures/sommelier/issues/1173>
Rhino links to "Real Yield ETH" and "Real Yield USD" deposit modals
https://github.com/strangelove-ventures/sommelier/issues/1173
"Real Yield ETH" link: https://app.rhino.fi/invest/YIELDETH/supply
"Real Yield USD" link:https://app.rhino.fi/invest/YIELDUSD/supply
=> buys and sell on exchange

src/pages/api/coingecko-simple-price.ts
Coingecko takes up to 4s to load, cache window is too small; this increases it to the same cache params as the slow graph queries.
=> Increase cache window for coingecko

.gitignore, src/data/strategies/defi-stars.ts, src/data/strategies/eth-btc-momentum.ts, src/data/strategies/eth-btc-trend.ts, src/data/strategies/fraximal.ts, src/data/strategies/real-yield-1inch.ts, src/data/strategies/real-yield-btc.ts, src/data/strategies/real-yield-ens.ts, src/data/strategies/real-yield-eth.ts, src/data/strategies/real-yield-link.ts, src/data/strategies/real-yield-snx.ts, src/data/strategies/real-yield-uni.ts, src/data/strategies/real-yield-usd.ts, src/data/strategies/steady-btc.ts, src/data/strategies/steady-eth.ts, src/data/strategies/steady-matic.ts, src/data/strategies/steady-uni.ts
Changed Platform Fee tooltip for all strategies to- “An annual charge on your deposited amount for the pro-rated period during which your deposit remains in the vault”
Changed platform fee for RYUSD to 0.00%
=> platform-fees-tooltip

src/pages/api/subgraph-status-block.ts, src/pages/api/subgraph-status-errors.ts
Adds two endpoints to be monitored by Better Stack. We will check on the subgraph block heigh to make sure we don't drift too far behind and also to see if there are indexing errors.
=> Add Subgraph alerting API endpoints

src/data/strategies/turbo-gho.ts
Added to Turbo GHO risks-
Because withdrawals can only be facilitated based on the available GHO-USDC liquidity in the market, it is possible to receive GHO upon withdrawal even if you deposited USDC.
=> turbo GHO risks

src/data/uiConfig.ts
We dont want to show "Bonding" related things if rewards program is via vesting contract as there is anyway no option to bond.
Current solution:
Expected solution:
=> turbo-somm&stETH&stETH2-hide-bonding-UI

src/data/actions/common/getStrategyData.ts
Removed Merkl rewards APY from Real Yield ETH and Real Yield USD on arbitrum.
=> Remove arbitrum yield enhancement
