PeggyJV/sommelier-strangelove

src/components/CurrentDeposits.tsx, src/components/_pages/PageCellar.tsx, src/utils/bigNumber.ts, src/utils/formatCurrentDeposits.ts, src/utils/urql.ts
Fixes #233
This PR corrects the decimal conversions for TVM values across the app.
=> chore: fix logic or value for cellar cap and current deps

src/pages/_document.tsx
Please outline path to new tests here:
eg. `./cypress/integration/path/to/test.spec.js`
=> fetch font over https

src/components/_cards/CellarCard/ValueManaged.tsx, src/components/_cards/PortfolioCard.tsx, src/components/_pages/PageCellar.tsx, src/context/aaveStakerContext.tsx, src/data/cellarDataMap.ts, src/pages/_app.tsx, src/pages/cellars/[id].tsx
Adds expected APY
- Pulls in somm price to calculate potential APY if a user adds a $10,000 deposit. This is summed up with the cellar APY to get expected APY.
- Adds a dynamic tootip to expected APY that updates with the correct values
=> Expected APY

src/components/_cards/CellarCard/Stats.tsx, src/components/_cards/PortfolioCard.tsx, src/components/_pages/PageCellar.tsx, src/context/aaveV2StablecoinCellar/index.tsx, src/pages/_app.tsx, src/utils/formatCurrency.ts
* fixes net value by calling convertToAssets with sum of cellar balance and staker balance
=> fix net value

src/components/_cards/CellarCard/Stats.tsx, src/components/_cards/PortfolioCard.tsx, src/context/aaveStakerContext.tsx
* Fixes rewards with a static call to claimAll on the staker
=> fix rewards

src/components/_modals/DepositModal.tsx
Deposits directly into the cellar instead of through the cellar router if selected asset is the same as the cellar's current asset.
This makes the transaction to deposit signficantly cheaper.
Please outline path to new tests here:
eg. `./cypress/integration/path/to/test.spec.js`
=> deposit directly into cellar if selected asset is active asset

src/components/_pages/PageCellar.tsx
Fix a hardcoded asset decimal value.
=> fix hardcoded asset decimals

src/pages/index.tsx
Adds meta tag for FB domain verification. We can revert this commit once verified.
=> FB Domain Verification

src/components/CurrentDeposits.tsx, src/components/_buttons/WithdrawButton.tsx, src/components/_cards/CellarCard/Stats.tsx, src/components/_cards/PortfolioCard.tsx, src/components/_charts/LineChart.tsx, src/components/_forms/WithdrawForm.tsx, src/components/_icons/SuccessIcon.tsx, src/components/_menus/ModalMenu/Menu.tsx, src/components/_modals/DepositModal.tsx, src/components/_modals/WithdrawModal.tsx, src/components/_pages/PageHome.tsx, src/hooks/chakra.tsx, src/hooks/web3/useHandleTransaction.tsx
Check [QA Somm app May 2022](https://docs.google.com/document/d/1yWKtJFbwhuvFPEytKM43lgSexb86Ef-ISmQqXVqEolA/edit?usp=sharing) for list of issues.
Please outline path to new tests here:
eg. `./cypress/integration/path/to/test.spec.js`
=> Fixes to the issues brought up by Yoni

src/components/_buttons/ConnectButton/index.tsx, src/components/_cards/PortfolioCard.tsx
=> Show connect wallet button instead of deposit and withdraw buttons when disconnected

src/pages/index.tsx
Reverts strangelove-ventures/sommelier#345
Domains have been verified we can remove the meta tags now.
=> Revert "FB Domain Verification"

src/pages/api/geo.ts
This PR provides a hotfix for restricted region access to the app.
=> Ip detection

src/components/_cards/PortfolioCard.tsx
Adds analytics tracking to claim
=> Analytics on Rewards

src/components/Layout.tsx, src/components/MobileWarningCTA.tsx
This PR introduces a notice CTA when users attempt to access the site from a mobile device.
=> Mobile notice

src/components/MobileWarningCTA.tsx
Fixes awkwardly placed CTA component on mobile
=> fixed placement

src/components/_menus/ModalMenu/Menu.tsx
Hotfix for incorrect form validation rule
=> fixed: validation rule

src/components/MobileWarningCTA.tsx, src/components/_menus/ModalMenu/Menu.tsx
=> Deposit validation rule fix

src/context/aaveStakerContext.tsx
Updates reward apy calc to:
```
(rewardRate * sommPrice) / ( totalDepositswithBoost + 10000 ) * (365 * 24 * 60 * 60) * 100
```
=> Apy: fix reward apy calc

src/components/Layout.tsx, src/components/MobileWarningCTA.tsx
Found solve for hiding UI on mobile
=> found solve for mobile

src/components/BreadCrumb.tsx, src/components/_cards/CellarCard/CellarCardDisplay.tsx, src/components/_menus/ModalMenu/Menu.tsx, src/components/_pages/PageCellar.tsx, src/components/_pages/PageHome.tsx
Fixes #298
Fixed UX issues on the Cards, Added text to the deposit modal, replaced (-)
<----- Aave text fix ------>
<----- Text to deposit modal ------>
<----- Replacing ------>
<----- Breadcrumb update ----->
https://www.figma.com/file/7IAQbLyzapnrow9sIcO77P/App?node-id=601%3A21278
=> 298 ux bugs

README.md
This PR introduces as much institutional knowledge as I could gather around data sourcing, our API route, and perhaps bizarre edge cases I've ran into during my time working in this codebase.
=> added more nuanced documentation to readme

src/components/_cards/CellarCard/ValueManaged.tsx, src/components/_pages/PageCellar.tsx, src/context/aaveStakerContext.tsx, src/context/aaveV2StablecoinCellar/index.tsx, src/utils/cellarApy.ts
Uses real APY for Cellar
- Fetch maxLocked, totalAssets, accrualPeriods from contract
- Add util function to calculate and format APY
- Update PageCellar and ValueManaged
=> Cellar APY

src/components/_cards/BridgeCard/EthereumAddress.tsx, src/components/_cards/BridgeCard/InputAmount.tsx, src/components/_cards/BridgeCard/index.tsx, src/components/_forms/BridgeForm.tsx
Closes #415 
Bridge form won't be appear if the account is not connected
=> feat: add account logic on bridge page

src/components/_buttons/UnstakeButton.tsx, src/components/_cards/BondingTableCard.tsx, src/components/_forms/UnstakeForm.tsx, src/components/_modals/UnstakeModal.tsx
Please outline path to new tests here:
eg. `./cypress/integration/path/to/test.spec.js`
=> fix unstake regression

src/components/CardStat.tsx, src/components/_buttons/ConnectButton/ConnectedPopover.tsx
Fixes #441 
Add tooltip a `color`
=> fix(ui): add tooltip color

src/hooks/web3/useBridgeTransaction.tsx
Add Bridge analytics event track
=> chore(analytics): add bridge analytics event track

src/components/_forms/BondForm/index.tsx, src/components/_forms/WithdrawForm.tsx
Fixes #434 
add Balance validation
=> feat(ui): add balance amount validation #434

src/generated/schema.json, src/generated/subgraph.ts, src/queries/get-all-time-tvl-by-address.graphql, src/queries/get-hourly-tvl-by-address.graphql, src/queries/get-weekly-tvl-by-address.graphql, src/utils/urql.ts
Part of #452 
Update graphql query
=> New data management/update graphql queries

src/data/cellarDataMap.ts
Part of #452 
new additional config for cellar data map to interact with `composite-data`
=> 1. New data management/cellar data map config

src/composite-data/actions/cellar/AAVE_V2_STABLE_CELLAR/fetchCellarData.ts, src/composite-data/actions/cellar/AAVE_V2_STABLE_CELLAR/fetchCellarShareBalance.ts, src/composite-data/actions/cellar/AAVE_V2_STABLE_CELLAR/fetchCellarUserData.ts, src/composite-data/actions/cellar/types.ts, src/composite-data/actions/staker/AAVE_STAKER/fetchStakerData.ts, src/composite-data/actions/staker/AAVE_STAKER/fetchStakerUserData.ts, src/composite-data/actions/staker/types.ts, src/composite-data/provider/compositeDataProvider.tsx
Part of #452
actions for every contract abi
=> 2. New data management/actions and provider

src/composite-data/hooks/cellar/useCellarData.tsx, src/composite-data/hooks/cellar/useCellarShareBalance.tsx, src/composite-data/hooks/cellar/useCellarUserData.tsx, src/composite-data/hooks/staker/useStakerData.tsx, src/composite-data/hooks/staker/useStakerUserData.tsx, src/composite-data/hooks/types.ts
Part of #452 
Hooks for handling actions
=> 3. New data management strategy/hooks for actions

src/composite-data/actions/calculate/cellarData.ts, src/composite-data/actions/calculate/userData.ts, src/composite-data/hooks/output/useOutputData.tsx, src/composite-data/hooks/output/useOutputUserData.tsx, src/composite-data/hooks/output/useUserBalances.tsx
Part of #452 
Exposable hooks and calculation functions
=> 4. New data management/output hooks and calculations

src/composite-data/context/performanceChartByAddressContext.tsx
Part of #452 
new dynamic reuseable perfomance chart context
=> 5. New data management/new perfomance chart context

src/composite-data/actions/cellar/AAVE_V2_STABLE_CELLAR/fetchCellarUserData.ts, src/composite-data/actions/cellar/types.ts, src/composite-data/actions/staker/AAVE_STAKER/fetchStakerUserData.ts, src/composite-data/actions/staker/types.ts
Part of #452 
change type of exposed data `BigNumber` to use `bignumber.js`
=> refactor: exposed data using bignumberjs

src/data/actions/AAVE_V2_STABLE_CELLAR/getActiveAsset.ts, src/data/actions/AAVE_V2_STABLE_CELLAR/getApy.ts, src/data/actions/AAVE_V2_STABLE_CELLAR/getCellarCap.ts, src/data/actions/AAVE_V2_STABLE_CELLAR/getCellarShareBalance.ts, src/data/actions/AAVE_V2_STABLE_CELLAR/getCurrentDeposits.ts, src/data/actions/AAVE_V2_STABLE_CELLAR/getNetValue.ts, src/data/actions/AAVE_V2_STABLE_CELLAR/getPnl.ts, src/data/actions/AAVE_V2_STABLE_CELLAR/getTvm.ts, src/data/actions/AAVE_V2_STABLE_CELLAR/getUserStakes.ts, src/data/actions/types.ts, src/data/context/performanceChartByAddressContext.tsx, src/data/hooks/useActiveAsset.ts, src/data/hooks/useApy.ts, src/data/hooks/useCellarCap.ts, src/data/hooks/useCreateContracts.tsx, src/data/hooks/useCurrentDeposits.ts, src/data/hooks/useNetValue.ts, src/data/hooks/usePnl.ts, src/data/hooks/useTvm.ts, src/data/hooks/useUserBalances.tsx, src/data/hooks/useUserStakes.tsx, src/data/provider/dataProvider.tsx
Part of #484 
This PR is for the new hooks per output
=> feat/data hook per output 

src/components/StrategyProvider.tsx, src/components/_cards/CellarDetailsCard.tsx, src/components/_cards/StrategyBreakdownCard/index.tsx, src/data/cellarDataMap.ts, src/data/hooks/useActiveAsset.ts, src/data/hooks/useApy.ts, src/data/hooks/useCellarCap.ts, src/data/hooks/useCreateContracts.tsx, src/data/hooks/useCurrentDeposits.ts, src/data/hooks/useNetValue.ts, src/data/hooks/usePnl.ts, src/data/hooks/useTvm.ts, src/data/hooks/useUserBalances.tsx, src/data/hooks/useUserStakes.tsx, src/data/types.ts
This is for code improvement and reusability
=> refactor: change type to enum

src/components/_menus/ModalMenu/Menu.tsx
Fixes #504 
Remove 50k deposit limit per wallet
=> remove: 50k deposit limit

src/components/_menus/ModalMenu/Menu.tsx
@henrio123 want me to move this update to production.
=> feat: remove 50k deposit limit per wallet

src/data/actions/CLEAR_GATE_CELLAR/getNetValue.ts, src/data/hooks/useNetValue.ts
This PR is for calculation of net value in clear gate cellars
=> feat: clear gate net value

src/components/_modals/DepositModal.tsx, src/data/hooks/useActiveAsset.ts, src/data/hooks/useApy.ts, src/data/hooks/useCellarCap.ts, src/data/hooks/useCurrentDeposits.ts, src/data/hooks/useNetValue.ts, src/data/hooks/usePnl.ts, src/data/hooks/useTvm.ts, src/data/hooks/useUserStakes.tsx
We need to put the address contract and other necessary params to the query key so react query can differentiate other cellars
=> chore: add necessary params to query key

src/components/_modals/DepositModal.tsx, src/data/actions/AAVE_V2_STABLE_CELLAR/depositAndSwap.ts, src/data/actions/CLEAR_GATE_CELLAR/depositAndSwap.ts, src/data/actions/types.ts, src/data/hooks/useDepositAndSwap.tsx
This PR is for clear gate depositAndSwap method
tested and suceed: https://etherscan.io/tx/0x75afebeb6ca70350255356120246a204079b7c5ae89bb2861b7c125a893bcf57
=> feat: clear gate cellar depositAndSwap

package.json, src/data/hooks/usePnl.ts, src/generated/schema.json, src/generated/subgraph.ts, src/queries/get-cellar.graphql, src/queries/get-position.graphql
Pulls in the updated v1.5 subgraph schema
=> Use testing subgraph in preparation for v1.5

src/components/_cards/BridgeCard/InputAmount.tsx, src/components/_cards/BridgeCard/InputSommelierAddress.tsx, src/theme/colors.ts, src/theme/shadows.ts
Fixes #430 
Fix bridge page UI UX
=> Fix: bridge page UI UX

src/data/actions/common/getTvm.ts, src/data/hooks/useTvm.ts
TVM for clear gate cellars using the same method with aave, We move it to `/common`
=> feat: tvm for clear gate cellars

src/components/HeroStrategy/hero-left.tsx, src/data/strategyPageContentData.tsx
Implement @henrio123 feedback on #539 , #540 
Update wording on strategy page
=> feat: update wording on strategy page

src/components/_buttons/DepositButton.tsx, src/components/_modals/DepositModal/ExchangeTab.tsx, src/components/_modals/DepositModal/SommelierTab.tsx, src/components/_modals/DepositModal/index.tsx, src/data/strategyPageContentData.tsx
Add exchange tab on deposit modal and swap buyUrl with the real url
=> feat: add exchange tab on deposit modal

src/components/CellarStats.tsx, src/components/HeroStrategy/hero-right.tsx, src/components/_cards/CellarCard/ValueManaged.tsx, src/components/_modals/DepositModal/index.tsx, src/components/_pages/PageCellar.tsx, src/data/strategies/eth-btc-momentum.ts, src/data/strategies/eth-btc-trend.ts
Related #568 
Implement design feedback, update wording, and fix ETH and BTC missing from Strategy assets
=> feat: cleargate strategies design improvements

src/data/strategyPageContentData.tsx
Links directly to swap page from the uniswap buy button. Also updates the alt tags for a few images.
=> Update Uniswap Buy URL to the swap page

src/components/FAQ/FAQTabs.tsx, src/components/Layout.tsx, src/components/MobileWarningCTA.tsx, src/data/cellarDataMap.ts
#576 
Remove mobile restriction on home page, update cellars order, and update mobile restriction text
=> Feat: update mobile view restriction

next.config.js, src/components/FAQ/FAQTabs.tsx, src/components/Layout.tsx, src/components/MobileWarningCTA.tsx, src/data/cellarDataMap.ts
Move staging site to production
=> prodsync 31 10 2022

src/components/_cards/CellarDetailsCard.tsx, src/data/strategies/aave-stable.ts, src/data/strategies/eth-btc-momentum.ts, src/data/strategies/eth-btc-trend.ts
#575
Update tooltip text based on feedback
=> feat: update tooltip texts

src/data/actions/AAVE_V2_STABLE_CELLAR/getPnl.ts, src/generated/schema.json, src/generated/subgraph.ts, src/queries/get-all-cellars.graphql, src/queries/get-cellar.graphql
Fetches current and historical share price `shareValue` for all cellars. Also updates fetching of day data to be in descending order.
=> pull share value and fetch day datas in desc order

src/components/CurrentDeposits.tsx, src/components/_cards/CellarCard/AboutCellar.tsx, src/components/_cards/CellarCard/CellarCardDisplay.tsx, src/components/_cards/CellarCard/ValueManaged.tsx
Fixes #541 
This fix UI bugs and adjustments
=> fix(ui): strategy cards

src/components/CellarStats.tsx, src/components/HeroStrategy/hero-right.tsx, src/components/PercentageText.tsx, src/components/_cards/CellarCard/ValueManaged.tsx, src/components/_pages/PageCellar.tsx, src/components/_pages/PageHome.tsx, src/data/CellarHomeDataMap.ts, src/data/hooks/useTokenPrice.ts, src/data/hooks/useWeekChange.ts
#583 
update the UI based on the first design iteration
Figma
[Add links to Figma files, documentation, etc.](https://www.figma.com/file/7IAQbLyzapnrow9sIcO77P/App?node-id=2195:101054)
=> feat: token price design changes

src/components/CellarStats.tsx, src/components/HeroStrategy/hero-right.tsx, src/components/PercentageText.tsx, src/components/_cards/CellarCard/ValueManaged.tsx, src/components/_pages/PageCellar.tsx, src/components/_pages/PageHome.tsx, src/data/CellarHomeDataMap.ts, src/data/hooks/useTokenPrice.ts, src/data/hooks/useWeekChange.ts
Move staging to production 4 November 2022
=> feat: move staging to production 4 11 2022

src/data/strategies/eth-btc-momentum.ts, src/data/strategies/eth-btc-trend.ts
update clear gate strategies description
=> Prod sync 

src/components/PercentageHeading.tsx, src/components/PercentageText.tsx, src/components/_icons/MinusIcon.tsx, src/components/_icons/PlusIcon.tsx
=> move design update feedback to production 14 November 2022

src/components/HeroStrategy/hero-right.tsx, src/components/PercentageText.tsx, src/components/_cards/CellarCard/AboutCellar.tsx, src/components/_cards/EthBtcPerfomanceCard.tsx, src/components/_charts/EthBtcChart.tsx, src/components/_charts/Legend.tsx, src/components/_pages/PageCellar.tsx, src/data/actions/common/getEthBtcGainChartData.ts, src/data/context/ethBtcChartContext.tsx, src/data/hooks/useDailyChange.ts, src/utils/chartHelper.ts
Chart Improvement
- refactor `useDailyChange` from use daily data to previous 24h data
- line chart prevent duplicate data 
- line chart improve accuracy 
- filter line chart by clicking the "legends"
- fix 0 percentage not showing
- date formating
https://user-images.githubusercontent.com/39829726/202289468-7657211d-2f3e-4b21-bf73-6a8d438f4624.mp4
=> Feat&fix/ chart improvement

src/components/_cards/EthBtcPerfomanceCard.tsx, src/components/_charts/EthBtcChart.tsx, src/data/actions/common/getEthBtcGainChartData.ts, src/utils/chartHelper.ts
Closes #609 
Adding line chart hover states
https://user-images.githubusercontent.com/39829726/202558826-1b959d6c-2588-4a48-90ad-090fb8444a22.mp4
=> Feat/ line chart hover state

package.json, src/generated/schema.json, src/generated/subgraph.ts, src/queries/get-all-cellars.graphql, src/queries/get-cellar.graphql
- Updates cellar fetch queries to get position distribution data
Target the `peggyjv/cellars` subgraph here: 
Pending: https://thegraph.com/hosted-service/subgraph/peggyjv/cellars?version=pending
Current (once syncd): https://thegraph.com/hosted-service/subgraph/peggyjv/cellars
=> Update subgraph queries to fetch position distribution

src/utils/config.ts
=> fix: url with dash

src/data/strategies/steady-btc.ts, src/data/strategies/steady-eth.ts, src/data/strategyPageContentData.tsx
- Fix steady btc ticker missing
- Update steady btc and steady eth description
=> Move staging to production 23 Nov 2022

src/data/strategyPageContentData.tsx
update steady btc & steady eth description
=> feat: update steady description

src/components/HeroStrategy/count-down.tsx, src/components/_buttons/ConnectButton/index.tsx, src/components/_cards/CellarCard/AboutCellar.tsx, src/components/_modals/DepositModal/SommelierTab.tsx, src/components/_pages/PageHome.tsx, src/data/strategies/steady-btc.ts, src/data/strategies/steady-eth.ts, src/utils/config.ts, src/utils/landingType.ts
=> Release/25 Nov 2022 

src/data/strategies/steady-btc.ts, src/data/strategies/steady-eth.ts
add depositors data in steady performance split
=> feat(data): add depositors data in steady performance split

src/components/HeroStrategy/hero-right.tsx, src/components/_cards/CellarCard/CellarCardDisplay.tsx, src/components/_cards/CellarCard/index.tsx, src/data/strategies/aave-stable.ts, src/data/strategies/eth-btc-momentum.ts, src/data/strategies/eth-btc-trend.ts, src/data/strategies/steady-btc.ts, src/data/strategies/steady-eth.ts, src/data/types.ts
Adds liquidity mining boosts and rewards countdown.
=> liquidity mining boosts

src/components/_cards/CellarCard/CellarCardDisplay.tsx, src/data/uiConfig.ts
=> Release/29 Nov 2022

src/components/HeroStrategy/hero-right.tsx, src/components/_buttons/ConnectButton/index.tsx, src/components/_cards/CellarCard/CellarCardDisplay.tsx, src/data/actions/CELLAR_V0815/getApy.ts, src/data/actions/CELLAR_V0815/getRewardsApy.ts, src/data/hooks/useApy.ts, src/data/uiConfig.ts
https://github.com/strangelove-ventures/sommelier/issues/696
Uses dynamic values for rewards APY
=> Use dynamic rewards apy

src/components/_forms/BondForm/index.tsx
reduce and adjust gas limit by estimating gas limit 
reduced from `600000`
=> fix: add bond estimate gas limit

package.json, src/components/Layout.tsx, src/components/Nav.tsx, src/components/_buttons/ConnectButton/ConnectedPopover.tsx, src/components/_cards/BridgeCard/index.tsx, src/components/_cards/CellarDetailsCard.tsx, src/components/_charts/EthBtcChart.tsx, src/components/_charts/TVLChart.tsx, src/components/_charts/UsdcChart.tsx, src/components/_pages/PageCellar.tsx, src/hooks/utils/useBetterMediaQuery.ts, src/pages/strategies/[id]/manage.tsx, yarn.lock
This PR is for improving DX, hydration error sometimes annoying when we open console to debug something.
`useMediaQuery` can cause hydration mismatch in react, because `useMediaQuery` hook uses `window.matchMedia` and doesn't work in SSR, hence the reason for the hydration mismatch. This hook only works for client-side only components.
=> Housekeeping&Fix/use media query react hydration error

src/components/_forms/BondForm/index.tsx, src/components/_forms/WithdrawForm.tsx, src/components/_modals/DepositModal/SommelierTab.tsx
Fixes #719 
add text after deposit
=> Feat: add text after deposit

src/components/_cards/PortfolioCard/index.tsx, src/components/_menus/ModalMenu/Menu.tsx, src/data/strategies/eth-btc-momentum.ts, src/data/strategies/eth-btc-trend.ts, src/data/strategies/steady-btc.ts, src/data/strategies/steady-eth.ts, src/data/tokenConfig.ts
Fixes #586 
Reference: https://stackoverflow.com/questions/35538509/sort-an-array-of-objects-based-on-another-array-of-ids
re order deposit tokens 
=> Feat: re order deposit tokens

src/components/_cards/BondingTableCard.tsx, src/components/_cards/CellarCard/CellarCardDisplay.tsx, src/components/_cards/PortfolioCard/index.tsx, src/utils/formatDistance.ts
create function to format date fns output, reference https://github.com/date-fns/date-fns/issues/1706. also already try to use different name for function but is not working
=> feat: date fns format based on design

src/components/HeroStrategy/hero-right.tsx, src/components/_cards/BondingTableCard.tsx, src/components/_cards/CellarCard/CellarCardDisplay.tsx, src/components/_cards/PortfolioCard/index.tsx
Remove rewards UI on home page(card), strategy landing pages, strategy details
=> feat: dynamically remove rewards UI

src/components/_modals/BuyOrSellModal.tsx, src/components/_modals/ModalWithExchangeTab.tsx, src/components/_tabs/ExchangeTab.tsx
analytics should trigger the selected platform
=> fix: platform selection analytics

src/data/actions/CELLAR_V0815/getApy.ts
See comments in PR to understand fix.
=> Fix APY calc for AAVE cellar

src/components/_modals/DepositModal/SommelierTab.tsx
#252 
add import lp token in toast after user successfully deposit
=> feat: add import lp token in toast

src/components/CellarStatsAutomated.tsx, src/components/CellarStatsYield.tsx, src/components/_pages/PageCellar.tsx
Refactor page cellar component to improve code readability
=> Refactor page cellar

public/assets/icons/hamburger.svg, src/components/Nav.tsx, src/components/_buttons/ConnectButton/ConnectWalletPopover.tsx, src/components/_buttons/ConnectButton/ConnectedPopover.tsx, src/components/_buttons/ConnectButton/MobileConnectedPopover.tsx, src/components/_buttons/ConnectButton/index.tsx, src/components/_icons/HamburgerIcon.tsx, src/theme/styles.ts, src/utils/navLinks.ts, src/utils/truncateWalletAddress.ts
Mobile nav follows the design on the figma
=> Feat  adjust mobile navigation

src/data/actions/CELLAR_V2/getApy.ts
=> calculate apy since inception for v2 cellars

package.json, src/components/_buttons/ConnectButton/ConnectWalletPopover.tsx, src/components/_modals/DepositModal/SommelierTab.tsx, src/utils/supabase.ts, yarn.lock
Sends the following events to Supabase so we can confirm our suspicion that some analytics are being dropped by users running ad blockers.
`wallet.connected`
`deposit.started`
`deposit.succeeded`
=> Track some events in postgres

src/components/_buttons/DepositButton.tsx, src/components/_modals/DepositModal/SommelierTab.tsx, src/components/_modals/DepositModal/index.tsx, src/components/_modals/NotifyModal.tsx
#918 
Adding deposit modal after deposit success
=> feat: add notify modal after deposit success

src/components/_cards/PortfolioCard/index.tsx
=> Fixes rendering issue when there is no day data for APY yet

src/data/actions/CELLAR_V2/getBaseApy.ts, src/data/actions/common/getAllStrategiesData.ts, src/data/actions/common/getRewardsApy.ts, src/data/actions/common/getStrategyData.ts, src/data/actions/common/getUserData.ts, src/data/actions/common/getUserDataAllStrategies.ts, src/data/hooks/useAllStrategiesData.ts, src/data/hooks/useStrategyData.ts, src/data/hooks/useUserDataAllStrategies.ts, src/data/hooks/useUserStrategyData.ts
hardcodes 18 decimals when calculating net value for RYETH.
left a comment to fix
=> Fix ryeth net value

src/data/actions/common/getUserData.ts
=> only multiply ryeth value by weth price

src/components/_cards/ApyPerfomanceCard.tsx, src/components/_modals/DepositModal/SommelierTab.tsx, src/components/_pages/PageCellar.tsx, src/data/context/apyChartContext.tsx
@henrio123 need to revert this in 1 week
=> Hardcode RY ETH APY to backtested 10% for a week

src/components/Footer/Overview.tsx, src/components/_menus/ModalMenu/Menu.tsx, src/components/_modals/DepositModal/SommelierTab.tsx, src/data/actions/common/getAllStrategiesData.ts, src/data/actions/common/getStrategyData.ts, src/data/hooks/useStrategyData.ts, src/data/strategies/defi-stars.ts, src/utils/config.ts
- added hiding coming soon value with `NEXT_PUBLIC_SHOW_ALL_MANAGE_PAGE`
- deposit asset only 1 asset deposit
=> Defi stars show value flag

src/components/HeroStrategy/hero-right.tsx, src/components/_buttons/WithdrawButton.tsx, src/components/_cards/PortfolioCard/index.tsx, src/components/_columns/StrategyDesktopColumn.tsx, src/components/_columns/StrategyMobileColumn.tsx, src/components/_columns/StrategyTabColumn.tsx, src/components/_tables/StrategyDate.tsx, src/components/_tables/StrategySection.tsx, src/data/actions/CELLAR_V2/getBaseApy.ts, src/data/actions/common/getChanges.ts, src/data/actions/common/getStrategyData.ts, src/data/strategies/aave-stable.ts, src/data/strategies/defi-stars.ts, src/data/strategies/eth-btc-momentum.ts, src/data/strategies/eth-btc-trend.ts, src/data/strategies/real-yield-eth.ts, src/data/strategies/real-yield-usd.ts, src/data/strategies/steady-btc.ts, src/data/strategies/steady-eth.ts, src/data/strategies/steady-matic.ts, src/data/strategies/steady-uni.ts, src/data/types.ts
=> feat: add deprecated strategies

src/components/_tables/StrategyDate.tsx, src/data/actions/common/getStrategyData.ts
=> fix: new strategy countdown

src/components/_charts/ApyChart.tsx, src/components/_charts/EthBtcChart.tsx, src/components/_charts/TokenPriceChart.tsx, src/components/_charts/UsdcChart.tsx
=> fix: fix chart quick fix

src/components/_cards/PortfolioCard/index.tsx
Fixes #1056 
change strategy detial pages text
=> feat: change strategy detial pages text

src/components/_cards/ApyPerfomanceCard.tsx, src/data/actions/common/getStrategyData.ts, src/data/context/apyChartContext.tsx, src/data/uiConfig.ts, src/utils/chartHelper.ts
Fixes #1047 
Enable and fix chat for real yield eth in detail page
- [fix: apy chart for ryeth detail page](https://github.com/strangelove-ventures/sommelier/commit/cb1dc7b743ccd92f6e8491983301578de48860b0)
=> fix: apy chart for ryeth detail page

src/components/_sidebar/PortofolioItem.tsx, src/components/_sidebar/YourPortofolio.tsx, src/components/_tables/StrategyTable.tsx, src/data/actions/common/getStrategyData.ts, src/data/actions/common/getTokenPrice.ts, src/data/actions/common/getUserData.ts, src/data/actions/common/getUserDataAllStrategies.ts, src/utils/formatCurrency.ts
Fixes #1052 
New Portofolio Design
=> feat: Add new portofolio design

src/components/_cards/PortfolioCard/index.tsx, src/data/actions/common/getPreviewShare.ts, src/data/hooks/useGetPreviewRedeem.ts
Fixes #1063 
fix calculation base asset value
=> fix: fix calculation base asset value

src/components/_columns/StrategyDesktopColumn.tsx
Fixes #1102 
hide tvl if not release yet
=> feat: hide tvl if not release yet

src/data/strategies/real-yield-1inch.ts, src/data/strategies/real-yield-ens.ts, src/data/strategies/real-yield-link.ts, src/data/strategies/real-yield-snx.ts, src/data/strategies/real-yield-uni.ts
=> feat: update launch date

src/data/strategies/real-yield-usd.ts
=> feat: new performance split for real-yield-usd

src/components/_cards/ApyPerfomanceCard.tsx, src/components/_pages/PageCellar.tsx, src/data/actions/common/getStrategyData.ts, src/data/uiConfig.ts
#1123 
Setup estimated APY, for home page, landing page, and detail page
=> feat: setup estimated apy

src/components/_columns/StrategyDesktopColumn.tsx, src/components/_columns/StrategyTabColumn.tsx
=> feat: add token price in table

src/components/HeroStrategy/hero-right.tsx, src/components/_cards/CellarCard/CellarCardDisplay.tsx
Fixes #1131 
remove expected string
=> fix: remove expected string

src/components/_cards/CellarDetailsCard.tsx, src/data/actions/CELLAR_V2/getBaseApy.ts, src/data/actions/common/getBaseApy.ts, src/data/actions/common/getRewardsApy.ts, src/data/strategies/defi-stars.ts, src/data/strategies/eth-btc-momentum.ts, src/data/strategies/eth-btc-trend.ts, src/data/strategies/real-yield-1inch.ts, src/data/strategies/real-yield-ens.ts, src/data/strategies/real-yield-eth.ts, src/data/strategies/real-yield-link.ts, src/data/strategies/real-yield-snx.ts, src/data/strategies/real-yield-uni.ts, src/data/strategies/real-yield-usd.ts, src/data/strategies/steady-btc.ts, src/data/strategies/steady-eth.ts, src/data/strategies/steady-matic.ts, src/data/strategies/steady-uni.ts, src/data/uiConfig.ts, src/utils/formatCurrency.ts
#1130 
update the number formatting to be more consistent
=> feat: change numbering format consistantly

src/components/_modals/DepositModal/SommelierTab.tsx, src/data/strategies/real-yield-eth.ts
=> feat: remove text due to high slippage in real yield eth

src/components/_cards/CellarDetailsCard.tsx, src/components/_pages/PageStrategy.tsx
FIXES #1151 
View more button 
Back button
=> feat: new button view more in detail pages

package.json, src/components/_buttons/DepositButton.tsx, src/components/_columns/StrategyDesktopColumn.tsx, src/components/_columns/StrategyMobileColumn.tsx, src/components/_columns/StrategyTabColumn.tsx, src/components/_layout/LayoutWithSidebar.tsx, src/components/_menus/ModalMenu/Menu.tsx, src/components/_modals/DepositModal/SommelierTab.tsx, src/components/_modals/ModalWithExchangeTab.tsx, src/components/_pages/PageHome.tsx, src/data/hooks/useDepositModalStore.ts, yarn.lock
=> feat: add deposit button in table

src/components/_buttons/DepositAndWithdrawButton.tsx, src/components/_cards/PortfolioCard/index.tsx, src/components/_columns/StrategyDesktopColumn.tsx, src/components/_columns/StrategyMobileColumn.tsx, src/components/_columns/StrategyTabColumn.tsx, src/components/_forms/WithdrawForm.tsx, src/components/_pages/PageHome.tsx, src/components/_tables/StrategyTable.tsx, src/data/hooks/useDepositModalStore.ts
=> Feat/define logic/deprecated strategies

src/data/uiConfig.ts
Fixes #1179 
enable apy for real yield link
=> feat: enable apy for real yield link

src/components/_buttons/DepositAndWithdrawButton.tsx, src/components/_cards/PortfolioCard/index.tsx, src/pages/index.tsx
Remove placeholder text & update buttons
=> Unblock frontend from subgraph

src/components/Nav.tsx, src/components/_buttons/DepositAndWithdrawButton.tsx, src/components/_cards/PortfolioCard/index.tsx, src/pages/index.tsx
Reverts temporary placeholder text for UI & deposit button updates.
=> Staging to Production 31.07

src/data/actions/common/getAllStrategiesData.ts, src/data/actions/common/getChanges.ts, src/data/actions/common/getUserDataAllStrategies.ts, src/data/hooks/useAllStrategiesData.ts, src/data/hooks/useUserDataAllStrategies.ts, src/generated/subgraph.ts, src/queries/get-all-strategies-data.graphql, src/utils/chartHelper.ts
Speeds up the queries for the cellar overviews.
=> Speed up data queries for initial cellar data

src/components/_cards/CellarDetailsCard.tsx
Fixes #<https://github.com/strangelove-ventures/sommelier/issues/1209>
Clean Details section -
Remove - Details page - Strategy Details button
Remove - Details page -Strategy details - View More button
Remove - Details page -Strategy details - TVL
Remove - Details page -Strategy details - Performance split
Switch Deposit assets and Fees
=> clean-details-section

src/components/_banners/InfoBanner.tsx, src/components/_pages/PageHome.tsx
Add's a fraximal upcoming incentive banner + reusable component for future use.
=> Add Fraximal upcoming vote banner + component for reuse in future

src/data/hooks/useAllStrategiesData.ts, src/data/hooks/useUserDataAllStrategies.ts, src/pages/api/graph-cellar-strategy-data.ts, src/queries/get-all-strategies-data.ts
Creates API + cache around expensive graph queries
=> Add caching of latency expensive graph queries

src/data/context/apyChartContext.tsx, src/data/context/ethBtcChartContext.tsx, src/data/context/tokenPriceChartContext.tsx, src/data/context/usdcChartContext.tsx, src/data/hooks/useStrategyData.ts, src/data/hooks/useUserStrategyData.ts, src/pages/api/coingecko-simple-price.ts, src/pages/api/graph-all-time-share-value-data.ts, src/pages/api/graph-individual-strat-data.ts, src/pages/api/graph-monthly-share-value-data.ts, src/pages/api/graph-weekly-share-value-data.ts, src/queries/get-all-strategies-data.ts, src/queries/get-all-time-share-value-data.ts, src/queries/get-coingecko-price.ts, src/queries/get-individual-strategy-data.ts, src/queries/get-monthly-share-value-data.ts, src/queries/get-weekly-share-value-data.ts
Cache individual strat data + share prices
=> Cache individual strat data + share prices

src/components/_modals/DepositModal/SommelierTab.tsx, src/data/uiConfig.ts
Add rhino link to RYBTC and clean up old out of date info in deposit widget
=> Add rhino link to RYBTC and clean up old out of date info in deposit widget

src/components/_layout/LayoutWithSidebar.tsx
=> Remove timeframe hover button

src/components/_pages/PageHome.tsx
=> RYE Incentive banner

src/components/_pages/PageHome.tsx
=> 11.08 Prod Deploy

src/components/_pages/PageHome.tsx
Update Aug 16 -> Aug 17 on RYETH incentive banner
=> Update ryeth banner

.gitignore, src/components/_pages/PageHome.tsx, src/data/strategies/defi-stars.ts, src/data/strategies/eth-btc-momentum.ts, src/data/strategies/eth-btc-trend.ts, src/data/strategies/fraximal.ts, src/data/strategies/real-yield-1inch.ts, src/data/strategies/real-yield-btc.ts, src/data/strategies/real-yield-ens.ts, src/data/strategies/real-yield-eth.ts, src/data/strategies/real-yield-link.ts, src/data/strategies/real-yield-snx.ts, src/data/strategies/real-yield-uni.ts, src/data/strategies/real-yield-usd.ts, src/data/strategies/steady-btc.ts, src/data/strategies/steady-eth.ts, src/data/strategies/steady-matic.ts, src/data/strategies/steady-uni.ts
=> 17.08 Staging to Prod

src/components/_pages/PageHome.tsx
=> Remove RYE incentive banner

.gitignore, src/components/_cards/PortfolioCard/index.tsx, src/data/strategies/aave-stable.ts, src/data/strategies/defi-stars.ts, src/data/strategies/eth-btc-momentum.ts, src/data/strategies/eth-btc-trend.ts, src/data/strategies/fraximal.ts, src/data/strategies/real-yield-1inch.ts, src/data/strategies/real-yield-btc.ts, src/data/strategies/real-yield-ens.ts, src/data/strategies/real-yield-eth.ts, src/data/strategies/real-yield-link.ts, src/data/strategies/real-yield-snx.ts, src/data/strategies/real-yield-uni.ts, src/data/strategies/real-yield-usd.ts, src/data/strategies/steady-btc.ts, src/data/strategies/steady-eth.ts, src/data/strategies/steady-matic.ts, src/data/strategies/steady-uni.ts, src/data/types.ts
Replacing "Strategy Details" links on Strategies "Manage" pages with links to "Strategy Dashboards"
=> Dashboard links

src/data/strategies/real-yield-usd.ts, src/data/strategyPageContentData.tsx
Change RYUSD small description text to: Maximize stablecoin yield across Aave, Compound, Uniswap, Morpho and the DAI Savings Rate.
=> ryusd-text

src/components/_tables/StrategyDate.tsx, src/utils/isComingSoon.ts
Launches should work on UTC time globally
=> Fix timezones for launches

src/components/_cards/BondingTableCard.tsx, src/components/_cards/PortfolioCard/index.tsx
Unbound to Unbond 
Ends in to Rewards program ends in
=> Unbond typo

src/components/_buttons/DepositAndWithdrawButton.tsx, src/components/_cards/CellarCard/AboutCellar.tsx
=> Enable deposits based on local timezone

src/data/strategies/turbo-sweth.ts, src/data/uiConfig.ts
=> Double swell reward rate

src/data/strategies/turbo-sweth.ts
=> fix performance fee

src/components/_pages/PageHome.tsx
=> Update turbo sweth banner duration

src/components/_cards/BondingTableCard.tsx, src/components/_cards/PortfolioCard/index.tsx, src/components/_tables/ApyRewardsSection.tsx, src/data/actions/common/getStrategyData.ts, src/data/strategies/turbo-sweth.ts, src/data/types.ts
=> Misc fixes around turbo sweth launch

src/components/_cards/BondingTableCard.tsx, src/components/_cards/PortfolioCard/index.tsx, src/components/_pages/PageHome.tsx, src/components/_tables/ApyRewardsSection.tsx, src/data/actions/common/getStrategyData.ts, src/data/strategies/turbo-sweth.ts, src/data/types.ts, src/data/uiConfig.ts
=> 24.08 Prod Deploy (misc fixes for turbo sweth launch)

src/components/_columns/SidebarColumn.tsx, src/components/_columns/StrategyDesktopColumn.tsx, src/components/_columns/StrategyMobileColumn.tsx, src/components/_columns/StrategyTabColumn.tsx, src/components/_tables/StrategySection.tsx, src/data/actions/common/getStrategyData.ts, src/data/strategies/real-yield-usd.ts, src/data/types.ts
=> RYUSD DSR label

src/data/uiConfig.ts
=> Staging to Main

src/data/strategies/turbo-sweth.ts, src/data/uiConfig.ts
=> Staging to Main (Morpho logo addition to turbo sweth)

src/components/CellarStatsYield.tsx, src/components/_cards/BondingTableCard.tsx, src/components/_cards/CellarDetailsCard.tsx, src/components/_cards/PortfolioCard/Rewards.tsx, src/components/_cards/PortfolioCard/index.tsx, src/components/_pages/PageHome.tsx, src/components/_tables/ApyRewardsSection.tsx, src/data/actions/common/getStrategyData.ts, src/data/actions/common/getUserDataAllStrategies.ts, src/data/strategies/turbo-sweth.ts, src/data/types.ts, src/data/uiConfig.ts
DO NOT MERGE + DEPLOY UNTIL Aug 30th once incentives are live
=> Prepare UI for Dual incentives for turbo sweth

src/components/Footer/index.tsx
=> remove-old-section

src/data/uiConfig.ts
=> Estimated APYS enabled for cellars w issues

src/data/uiConfig.ts
This reverts commit 9e0c91a421576a14c8af6e26412c2fc1f99d24be.
=> Revert "Estimated APYS enabled for cellars w issues"

src/data/uiConfig.ts
=> 31.08 Prod Deploy Resume live APYs

src/components/_columns/StrategyDesktopColumn.tsx, src/components/_columns/StrategyTabColumn.tsx, src/data/uiConfig.ts
1. "APY Since Inception" to "Net APY"
2. "Base APY" to "APY Since Inception"
3. Base APY & Rewards to "Net APY" + tooltip
=> APY definitions

src/components/_pages/PageHome.tsx, src/pages/api/cellar-preview-redeem.ts, src/pages/api/cellar-redeemable-reserves.ts, src/pages/api/coingecko-simple-price.ts, src/pages/api/sommelier-api-all-time-share-value-data.ts, src/pages/api/sommelier-api-hourly-share-value-data.ts, src/pages/api/sommelier-api-individual-strat-data.ts, src/pages/api/sommelier-api-monthly-share-value-data.ts, src/pages/api/sommelier-api-weekly-share-value-data.ts
=> Prod Deploy -- Fixed error logging

src/components/_columns/StrategyDesktopColumn.tsx, src/components/_columns/StrategyTabColumn.tsx
=> APY-sorting-fix

src/components/_buttons/BondButton.tsx, src/components/_cards/BondingTableCard.tsx, src/components/_cards/PortfolioCard/index.tsx, src/components/_forms/BondForm/index.tsx, src/data/uiConfig.ts
https://docs.google.com/document/d/1RBJSKgVJbQilRG9JAJSESvlNtR_cZ3hN6lC4zd7lZdQ/edit
=> Bonding unbonding definitions

src/components/_tables/ApyRewardsSection.tsx, src/data/strategies/turbo-sweth.ts, src/data/uiConfig.ts
=> Staging to Main (Update pearl reward rate)

src/components/_columns/StrategyDesktopColumn.tsx, src/components/_columns/StrategyTabColumn.tsx
=> tab-apy-sorting-fix-3

src/hooks/web3/useBridgeSommToEthTx.tsx, src/pages/bridge/index.tsx
=> Change RPCs from Strangelove to Polkachu

src/components/_pages/PageHome.tsx
=> Staging to Main(Add turbo sweth oct incentives to banner)

src/components/_pages/PageHome.tsx
=> Staging to Main(Update banner)

src/components/_columns/StrategyDesktopColumn.tsx, src/components/_columns/StrategyMobileColumn.tsx, src/components/_columns/StrategyTabColumn.tsx, src/components/_sidebar/PortofolioItem.tsx, src/components/_tables/StrategySection.tsx, src/data/actions/common/getStrategyData.ts, src/theme/styles.ts
Makes base logos asset to be more informative + adds sorting
=> Change cellar icons on main page to base asset logo

src/components/_columns/StrategyDesktopColumn.tsx, src/components/_columns/StrategyMobileColumn.tsx, src/components/_columns/StrategyTabColumn.tsx, src/components/_pages/PageHome.tsx, src/components/_sidebar/PortofolioItem.tsx, src/components/_tables/StrategySection.tsx, src/data/actions/common/getStrategyData.ts, src/theme/styles.ts
=> Staging to Main (hange cellar icons on main page to base asset logo)

src/components/CellarStatsAutomated.tsx, src/components/HeroStrategy/count-down.tsx, src/components/HeroStrategy/hero-right.tsx, src/components/Highlight/index.tsx, src/components/_buttons/ConnectButton/ConnectWalletPopover.tsx, src/components/_buttons/DepositAndWithdrawButton.tsx, src/components/_buttons/DepositButton.tsx, src/components/_buttons/UnstakeButton.tsx, src/components/_buttons/WithdrawButton.tsx, src/components/_cards/BondingTableCard.tsx, src/components/_cards/PortfolioCard/Rewards.tsx, src/components/_columns/StrategyDesktopColumn.tsx, src/components/_forms/BondForm/BondingPeriodOptions.tsx, src/components/_forms/BondForm/index.tsx, src/components/_forms/UnstakeForm.tsx, src/components/_forms/WithdrawForm.tsx, src/components/_menus/ModalMenu/Menu.tsx, src/components/_modals/BuyOrSellModal.tsx, src/components/_modals/DepositModal/SommelierTab.tsx, src/components/_pages/PageHome.tsx, src/components/_sidebar/PortofolioItem.tsx, src/components/_tables/SidebarTable.tsx, src/components/_tabs/ExchangeTab.tsx, src/context/geoContext.tsx, src/hooks/web3/useBridgeEthToSommTx.tsx, src/hooks/web3/useBridgeSommToEthTx.tsx
**Updated tracking for:**
vaults/detail
vaults/trading
vaults/yield
Wallet connected
Wallet disconnected
=> Improve tracking

src/components/CellarStatsAutomated.tsx, src/components/HeroStrategy/count-down.tsx, src/components/HeroStrategy/hero-right.tsx, src/components/Highlight/index.tsx, src/components/_buttons/ConnectButton/ConnectWalletPopover.tsx, src/components/_buttons/DepositAndWithdrawButton.tsx, src/components/_buttons/DepositButton.tsx, src/components/_buttons/UnstakeButton.tsx, src/components/_buttons/WithdrawButton.tsx, src/components/_cards/BondingTableCard.tsx, src/components/_cards/PortfolioCard/Rewards.tsx, src/components/_forms/BondForm/BondingPeriodOptions.tsx, src/components/_forms/BondForm/index.tsx, src/components/_forms/UnstakeForm.tsx, src/components/_forms/WithdrawForm.tsx, src/components/_menus/ModalMenu/Menu.tsx, src/components/_modals/BuyOrSellModal.tsx, src/components/_modals/DepositModal/SommelierTab.tsx, src/components/_sidebar/PortofolioItem.tsx, src/components/_tables/SidebarTable.tsx, src/components/_tabs/ExchangeTab.tsx, src/context/geoContext.tsx, src/hooks/web3/useBridgeEthToSommTx.tsx, src/hooks/web3/useBridgeSommToEthTx.tsx
=> Remove unnecessary trackers

src/components/_cards/CellarDetailsCard.tsx, src/components/_cards/StrategyBreakdownCard/index.tsx
**Currently Vault Details-**
**Fix-**
=> vault details mobile responsive

src/components/_pages/PageHome.tsx
=> remove-banner

src/components/_modals/DepositModal/SommelierTab.tsx
Duplicated "Risks" content into Deposit modals per Vault.
=> Risks in deposit modal

src/components/_modals/DepositModal/SommelierTab.tsx, src/components/_pages/PageHome.tsx
=> Staging to Main (risks-in-deposit-modal)

src/components/_forms/WithdrawForm.tsx, src/components/_modals/DepositModal/SommelierTab.tsx
=> Wording fixes

src/components/_pages/PageHome.tsx, src/data/actions/common/getStrategyData.ts, src/data/strategies/turbo-steth.ts, src/data/uiConfig.ts
=> Staging to Main(Estimate APY and Banner Updates)

src/hooks/web3/useBridgeEthToSommTx.tsx
Do not require somm approvals every time a gravity tx is created if sufficient approvals exist
=> Check Gravity eth -> somm approvals

src/components/_pages/PageHome.tsx
remove GHO banner when rewards start
=> remove-GHO-banner

src/components/_tables/ApyRewardsSection.tsx, src/data/strategies/turbo-gho.ts, src/data/types.ts
"GHO Rewards ends in 7 days"
Changed to: "Rewards updated weekly"
=> GHO-rewards-wording

src/components/_tables/ApyRewardsSection.tsx, src/data/strategies/turbo-gho.ts, src/data/types.ts
updated "GHO Somm rewards" tooltip
=> Gho somm rewards weekly

src/components/_pages/PageHome.tsx
=> remove-swETH-banner

src/components/_pages/PageHome.tsx, src/data/actions/common/getStrategyData.ts, src/data/cellarDataMap.ts, src/data/strategies/turbo-steth.ts, src/data/uiConfig.ts
=> Remove stETH Rewards

src/data/strategies/turbo-gho.ts
=> remove GHO rewards

src/data/strategies/turbo-sweth.ts, src/data/uiConfig.ts
https://github.com/strangelove-ventures/sommelier/pull/1464
=> 12/10 -- Prod Deploy -> turbo-somm&stETH&stETH2-hide-bonding-UI 

src/components/_pages/PageHome.tsx, src/data/uiConfig.ts
1. Real Yield BTC banner-
"A new incentive program for Real Yield BTC is progressing through governance. If it passes, rewards will begin December 22nd."
2. in the Turbo swETH pop-up on the table page, 7D changed to 30D
=> Real Yield BTC banner

src/components/_pages/PageHome.tsx, src/data/strategies/turbo-sweth.ts, src/data/uiConfig.ts
https://github.com/strangelove-ventures/sommelier/pull/1478
=> 12/19 Prod Deploy -- Real Yield BTC banner

src/data/strategies/fraximal.ts, src/data/strategies/real-yield-1inch.ts, src/data/strategies/real-yield-btc.ts, src/data/strategies/real-yield-ens.ts, src/data/strategies/real-yield-eth.ts, src/data/strategies/real-yield-link.ts, src/data/strategies/real-yield-snx.ts, src/data/strategies/real-yield-uni.ts, src/data/strategies/turbo-gho.ts, src/data/strategies/turbo-steth.ts, src/data/strategies/turbo-sweth.ts, src/data/strategyPageContentData.tsx
=> remove define logic

src/components/_pages/PageHome.tsx
=> remove banner

src/data/strategies/turbo-steth-steth-deposit.ts, src/data/uiConfig.ts
=> stETH2 live 7D APY

src/components/_filters/DepositTokenFilter.tsx, src/components/_menus/ModalMenu/Menu.tsx, src/components/_modals/DepositModal/SommelierTab.tsx
https://github.com/strangelove-ventures/sommelier/pull/1492
=> 01/01 Prod Deploy -- Adjust deposit for max decimal input 

src/components/_cards/SnapshotCard/index.tsx
=> snapshot-Wrong Network-fix

src/components/_cards/SnapshotCard/index.tsx, src/utils/estimateGasLimit.ts
=> Deploy snapshot fix

src/components/_cards/BridgeCard/InputAmount.tsx
=> Somm token formatting

src/data/strategies/real-yield-eth-arb.ts
=> Fix merge conflict

src/components/_pages/PageCellar.tsx, src/data/actions/common/getStrategyData.ts
=> 08/28 Prod Deploy -- Remove arbitrum yield enhancement

src/components/_cards/PortfolioCard/MerklePoints/MerklePoints.tsx, src/data/actions/common/getStrategyData.ts
=> 08/29 Prod Deploy -- Typos in Merkl rewards

src/components/_cards/PortfolioCard/MerklePoints/MerklePoints.tsx, src/components/_pages/PageCellar.tsx
https://github.com/PeggyJV/sommelier-strangelove/pull/1741
=> op-rew-batch-date

src/components/_sections/TopLaunchBanner.tsx, src/pages/strategies/[id]/manage.tsx
Manage route: dynamically import PageCellar (ssr:false) to avoid EMFILE.
=> Alpha STETH fixes: SSR crash

src/pages/api/rpc-report.ts
- Add runtime debug headers to `/api/rpc-report` to verify KV wiring on staging.
- New headers: `x-somm-kv-source` (ATTRIB|KV), `x-somm-kv-host` (Upstash host), `x-somm-idx-sample` (queried index key).
- No change to response body or query params; only observability.
- Purpose: quickly confirm the report reads the same Upstash instance as ingestion, resolving header-only CSV reports in staging.
=> attrib: add runtime KV debug headers to /api/rpc-report
